version: '3.9'
services:
  strapi:
    image: node:20-alpine
    working_dir: /opt/app
    environment:
      NODE_ENV: production
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - ../cms:/opt/app
      - strapi_uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - strapi_db:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - strapi
    restart: unless-stopped

volumes:
  strapi_db:
  strapi_uploads:
  caddy_data:
  caddy_config:
